from mdp import *

original_state = #put state here
last_placed_object = #extract this from the state somehow

rows_policy_outcome = #call the rows policy on the state not including last_placed_object
depth_img = #get a depth image from this

possible_other_placements = [] #other ways to place the last_placed_object
depth_imgs = [] #depth images for each other placement

heatmap = [[]] # call Value function on each state generated by using the other placements
